In [1]:
import numpy as np
import pandas as pd
import numpy.random as rd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn import model_selection

In [12]:
data = pd.read_csv(r"C:\Users\Vinod\Desktop\major project\tesla_stocks.csv")


Row_list =[] 
#Row_list1 = []

# Iterate over each row 
for index, rows in data.iterrows(): 
    # Create list for the current row 
    my_list =[rows['Open'], rows['High'], rows['Low'], rows['Close'], rows['Volume']] 
    
    # append the list to the final list 
    Row_list.append(my_list)
    
print(Row_list[:10])
print(len(Row_list))

[[42.25, 43.33000183105469, 42.08000183105469, 42.98400115966797, 37167000], [43.09600067138672, 45.4000015258789, 42.854000091552734, 45.00600051879883, 61584000], [45.74399948120117, 46.94800186157226, 44.512001037597656, 44.948001861572266, 63579000], [45.02199935913086, 45.55400085449219, 44.21200180053711, 45.2859992980957, 32875500], [44.599998474121094, 45.38000106811523, 43.27000045776367, 43.92399978637695, 59317500], [43.24399948120117, 44.43600082397461, 43.099998474121094, 44.37200164794922, 41010500], [44.64799880981445, 45.17200088500977, 44.20399856567383, 44.72800064086914, 28754000], [44.87799835205078, 45.06800079345703, 43.89799880981445, 43.95199966430664, 30910500], [44.0620002746582, 45.44599914550781, 43.61999893188477, 43.854000091552734, 42536000], [43.88999938964844, 44.58000183105469, 43.47000122070313, 44.56800079345703, 31698500]]
43

In [13]:
trend = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trend.append(1)
    elif row[3] - row[0] < 0:
        trend.append(-1)
    elif row[3] - row[0] == 0:
        trend.append(0)
            
print(trend)
print(len(trend))
          
trendString = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trendString.append('Positive')
    elif row[3] - row[0] < 0:
        trendString.append('Negative')
    elif row[3] - row[0] == 0:
        trendString.append('Neutral')
        
print(trendString)

[1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1]
43
['Positive', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative']

In [14]:
data["Trend"] = trend
data["TrendString"] = trendString

In [15]:
data

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Trend,TrendString
0,2019-06-14,42.250000,43.330002,42.080002,42.984001,37167000,0,0,1,Positive
1,2019-06-17,43.096001,45.400002,42.854000,45.006001,61584000,0,0,1,Positive
2,2019-06-18,45.743999,46.948002,44.512001,44.948002,63579000,0,0,-1,Negative
3,2019-06-19,45.021999,45.554001,44.212002,45.285999,32875500,0,0,1,Positive
4,2019-06-20,44.599998,45.380001,43.270000,43.924000,59317500,0,0,-1,Negative
5,2019-06-21,43.243999,44.436001,43.099998,44.372002,41010500,0,0,1,Positive
6,2019-06-24,44.647999,45.172001,44.203999,44.728001,28754000,0,0,1,Positive
7,2019-06-25,44.877998,45.068001,43.897999,43.952000,30910500,0,0,-1,Negative
8,2019-06-26,44.062000,45.445999,43.619999,43.854000,42536000,0,0,-1,Negative
9,2019-06-27,43.889999,44.580002,43.470001,44.568001,31698500,0,0,1,Positive
10,2019-06-28,44.198002,45.034000,44.160000,44.692001,34257000,0,0,1,Positive
11,2019-07-01,46.042000,46.619999,45.256001,45.433998,41067000,0,0,-1,Negative
12,2019-07-02,45.778000,45.830002,44.444000,44.910000,46295000,0,0,-1,Negative
13,2019-07-03,47.877998,48.313999,46.902000,46.980000,71005500,0,0,-1,Negative
14,2019-07-05,46.914001,47.090000,46.160000,46.619999,35328500,0,0,-1,Negative
15,2019-07-08,46.248001,46.450001,45.731998,46.068001,29402500,0,0,-1,Negative
16,2019-07-09,45.793999,46.200001,45.456001,46.012001,30954000,0,0,1,Positive
17,2019-07-10,46.830002,47.787998,46.627998,47.784000,45728500,0,0,1,Positive
18,2019-07-11,47.627998,48.299999,47.160000,47.720001,37572000,0,0,1,Positive
19,2019-07-12,47.950001,49.076000,47.942001,49.015999,46002500,0,0,1,Positive
20,2019-07-15,49.599998,50.883999,48.972000,50.700001,55000500,0,0,1,Positive
21,2019-07-16,49.860001,50.706001,49.585999,50.476002,40745000,0,0,1,Positive
22,2019-07-17,51.133999,51.661999,50.669998,50.972000,48823500,0,0,-1,Negative
23,2019-07-18,51.009998,51.150002,50.377998,50.708000,23793000,0,0,-1,Negative
24,2019-07-19,51.138000,51.992001,50.924000,51.636002,35242000,0,0,1,Positive
25,2019-07-22,51.750000,52.430000,50.838001,51.136002,34212000,0,0,-1,Negative
26,2019-07-23,51.341999,52.096001,50.900002,52.034000,25115500,0,0,1,Positive
27,2019-07-24,51.834000,53.214001,51.632000,52.976002,55364000,0,0,1,Positive
28,2019-07-25,46.700001,46.900002,45.110001,45.764000,112091500,0,0,-1,Negative
29,2019-07-26,45.383999,46.051998,44.450001,45.608002,50138500,0,0,1,Positive
30,2019-07-29,45.417999,47.188000,45.206001,47.153999,46366500,0,0,1,Positive
31,2019-07-30,46.580002,48.672001,46.436001,48.452000,40545000,0,0,1,Positive
32,2019-07-31,48.599998,49.335999,47.330002,48.321999,45891000,0,0,-1,Negative
33,2019-08-01,48.529999,48.902000,46.354000,46.770000,41297500,0,0,-1,Negative
34,2019-08-02,46.270000,47.254002,45.846001,46.868000,30682500,0,0,1,Positive
35,2019-08-05,45.919998,46.273998,45.155998,45.664001,35141500,0,0,-1,Negative
36,2019-08-06,46.375999,46.500000,45.150002,46.150002,27821000,0,0,-1,Negative
37,2019-08-07,45.299999,46.714001,45.160000,46.683998,23882500,0,0,1,Positive
38,2019-08-08,46.889999,47.959999,46.529999,47.660000,26371500,0,0,1,Positive
39,2019-08-09,47.209999,47.792000,46.762001,47.001999,19491000,0,0,-1,Negative
40,2019-08-12,46.598000,47.153999,45.750000,45.801998,23319500,0,0,-1,Negative
41,2019-08-13,45.762001,47.200001,45.509998,47.000000,24240500,0,0,1,Positive
42,2019-08-14,46.242001,46.299999,43.338001,43.924000,47813000,0,0,-1,Negative

In [18]:
data.drop(['Dividends', 'Stock Splits'], axis=1)

,Date,Open,High,Low,Close,Volume,Trend,TrendString
0,2019-06-14,42.250000,43.330002,42.080002,42.984001,37167000,1,Positive
1,2019-06-17,43.096001,45.400002,42.854000,45.006001,61584000,1,Positive
2,2019-06-18,45.743999,46.948002,44.512001,44.948002,63579000,-1,Negative
3,2019-06-19,45.021999,45.554001,44.212002,45.285999,32875500,1,Positive
4,2019-06-20,44.599998,45.380001,43.270000,43.924000,59317500,-1,Negative
5,2019-06-21,43.243999,44.436001,43.099998,44.372002,41010500,1,Positive
6,2019-06-24,44.647999,45.172001,44.203999,44.728001,28754000,1,Positive
7,2019-06-25,44.877998,45.068001,43.897999,43.952000,30910500,-1,Negative
8,2019-06-26,44.062000,45.445999,43.619999,43.854000,42536000,-1,Negative
9,2019-06-27,43.889999,44.580002,43.470001,44.568001,31698500,1,Positive
10,2019-06-28,44.198002,45.034000,44.160000,44.692001,34257000,1,Positive
11,2019-07-01,46.042000,46.619999,45.256001,45.433998,41067000,-1,Negative
12,2019-07-02,45.778000,45.830002,44.444000,44.910000,46295000,-1,Negative
13,2019-07-03,47.877998,48.313999,46.902000,46.980000,71005500,-1,Negative
14,2019-07-05,46.914001,47.090000,46.160000,46.619999,35328500,-1,Negative
15,2019-07-08,46.248001,46.450001,45.731998,46.068001,29402500,-1,Negative
16,2019-07-09,45.793999,46.200001,45.456001,46.012001,30954000,1,Positive
17,2019-07-10,46.830002,47.787998,46.627998,47.784000,45728500,1,Positive
18,2019-07-11,47.627998,48.299999,47.160000,47.720001,37572000,1,Positive
19,2019-07-12,47.950001,49.076000,47.942001,49.015999,46002500,1,Positive
20,2019-07-15,49.599998,50.883999,48.972000,50.700001,55000500,1,Positive
21,2019-07-16,49.860001,50.706001,49.585999,50.476002,40745000,1,Positive
22,2019-07-17,51.133999,51.661999,50.669998,50.972000,48823500,-1,Negative
23,2019-07-18,51.009998,51.150002,50.377998,50.708000,23793000,-1,Negative
24,2019-07-19,51.138000,51.992001,50.924000,51.636002,35242000,1,Positive
25,2019-07-22,51.750000,52.430000,50.838001,51.136002,34212000,-1,Negative
26,2019-07-23,51.341999,52.096001,50.900002,52.034000,25115500,1,Positive
27,2019-07-24,51.834000,53.214001,51.632000,52.976002,55364000,1,Positive
28,2019-07-25,46.700001,46.900002,45.110001,45.764000,112091500,-1,Negative
29,2019-07-26,45.383999,46.051998,44.450001,45.608002,50138500,1,Positive
30,2019-07-29,45.417999,47.188000,45.206001,47.153999,46366500,1,Positive
31,2019-07-30,46.580002,48.672001,46.436001,48.452000,40545000,1,Positive
32,2019-07-31,48.599998,49.335999,47.330002,48.321999,45891000,-1,Negative
33,2019-08-01,48.529999,48.902000,46.354000,46.770000,41297500,-1,Negative
34,2019-08-02,46.270000,47.254002,45.846001,46.868000,30682500,1,Positive
35,2019-08-05,45.919998,46.273998,45.155998,45.664001,35141500,-1,Negative
36,2019-08-06,46.375999,46.500000,45.150002,46.150002,27821000,-1,Negative
37,2019-08-07,45.299999,46.714001,45.160000,46.683998,23882500,1,Positive
38,2019-08-08,46.889999,47.959999,46.529999,47.660000,26371500,1,Positive
39,2019-08-09,47.209999,47.792000,46.762001,47.001999,19491000,-1,Negative
40,2019-08-12,46.598000,47.153999,45.750000,45.801998,23319500,-1,Negative
41,2019-08-13,45.762001,47.200001,45.509998,47.000000,24240500,1,Positive
42,2019-08-14,46.242001,46.299999,43.338001,43.924000,47813000,-1,Negative

In [20]:
data.to_csv(r'C:\Users\Vinod\Desktop\major project\tesla_stocks.csv')

In [21]:
data = pd.read_csv(r"C:\Users\Vinod\Desktop\major project\amazon_stocks.csv")


Row_list =[] 
#Row_list1 = []

# Iterate over each row 
for index, rows in data.iterrows(): 
    # Create list for the current row 
    my_list =[rows['Open'], rows['High'], rows['Low'], rows['Close'], rows['Volume']] 
    
    # append the list to the final list 
    Row_list.append(my_list)
    
print(Row_list[:10])
print(len(Row_list))

[[1864.0, 1876.0, 1859.0, 1869.6700439453125, 2851200], [1876.5, 1895.68994140625, 1875.449951171875, 1886.030029296875, 2634300], [1901.3499755859373, 1921.6700439453125, 1899.7900390625, 1901.3699951171875, 3895700], [1907.8399658203125, 1919.5799560546875, 1892.469970703125, 1908.7900390625, 2895300], [1933.3299560546875, 1935.199951171875, 1905.800048828125, 1918.18994140625, 3217200], [1916.0999755859373, 1925.949951171875, 1907.5799560546875, 1911.300048828125, 3933600], [1912.6600341796875, 1916.8599853515625, 1901.300048828125, 1913.9000244140625, 2283000], [1911.8399658203125, 1916.3900146484373, 1872.4200439453125, 1878.27001953125, 3012300], [1892.47998046875, 1903.800048828125, 1887.3199462890625, 1897.8299560546875, 2441900], [1902.0, 1911.239990234375, 1898.0400390625, 1904.280029296875, 2141700]]
43

In [22]:
trend = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trend.append(1)
    elif row[3] - row[0] < 0:
        trend.append(-1)
    elif row[3] - row[0] == 0:
        trend.append(0)
            
print(trend)
print(len(trend))
          
trendString = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trendString.append('Positive')
    elif row[3] - row[0] < 0:
        trendString.append('Negative')
    elif row[3] - row[0] == 0:
        trendString.append('Neutral')
        
print(trendString)

[1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1]
43
['Positive', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative']

In [23]:
data["Trend"] = trend
data["TrendString"] = trendString

In [24]:
data.to_csv(r'C:\Users\Vinod\Desktop\major project\amazon_stocks.csv')

In [28]:
data = pd.read_csv(r"C:\Users\Vinod\Desktop\major project\apple_stocks.csv")


Row_list =[] 
#Row_list1 = []

# Iterate over each row 
for index, rows in data.iterrows(): 
    # Create list for the current row 
    my_list =[rows['Open'], rows['High'], rows['Low'], rows['Close'], rows['Volume']] 
    
    # append the list to the final list 
    Row_list.append(my_list)
    
print(Row_list[:10])
print(len(Row_list))

[[47.00600272579293, 47.50661315879119, 46.69925512740545, 47.29802703857422, 75046000], [47.337277689886754, 47.842800768511154, 47.15813817946515, 47.5802230834961, 58676400], [48.11029536078598, 49.15078084575062, 47.90416186785647, 48.69924926757813, 106204000], [49.00108134458432, 49.050163950684784, 48.419489158169654, 48.55691146850586, 84496800], [49.170407162934715, 49.229304044243285, 48.59617661196541, 48.94709777832031, 86056000], [48.785132855865676, 49.28819960485812, 48.62562187744136, 48.78022384643555, 191202400], [48.7213259327641, 49.118873309673006, 48.63052985485729, 48.73114395141602, 72881600], [48.69433516081453, 48.89801599958522, 47.92378540358039, 47.99250030517578, 84281200], [48.5323750777201, 49.32255712564375, 48.429308342487964, 49.03053283691406, 104270000], [49.15077403807672, 49.464886988600654, 48.974090886092824, 49.01580810546875, 83598800]]
43

In [29]:
trend = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trend.append(1)
    elif row[3] - row[0] < 0:
        trend.append(-1)
    elif row[3] - row[0] == 0:
        trend.append(0)
            
print(trend)
print(len(trend))
          
trendString = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trendString.append('Positive')
    elif row[3] - row[0] < 0:
        trendString.append('Negative')
    elif row[3] - row[0] == 0:
        trendString.append('Neutral')
        
print(trendString)

[1, 1, 1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, 1, 1, -1]
43
['Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative']

In [30]:
data["Trend"] = trend
data["TrendString"] = trendString

In [31]:
data.to_csv(r'C:\Users\Vinod\Desktop\major project\apple_stocks.csv')

In [32]:
data = pd.read_csv(r"C:\Users\Vinod\Desktop\major project\google_stocks.csv")


Row_list =[] 
#Row_list1 = []

# Iterate over each row 
for index, rows in data.iterrows(): 
    # Create list for the current row 
    my_list =[rows['Open'], rows['High'], rows['Low'], rows['Close'], rows['Volume']] 
    
    # append the list to the final list 
    Row_list.append(my_list)
    
print(Row_list[:10])
print(len(Row_list))

[[1089.739990234375, 1094.760009765625, 1081.47998046875, 1086.300048828125, 1229100], [1089.0999755859377, 1101.280029296875, 1088.0, 1093.8900146484377, 988500], [1111.5, 1118.780029296875, 1100.7900390625, 1105.239990234375, 1726300], [1107.239990234375, 1109.4300537109377, 1096.030029296875, 1104.510009765625, 1335700], [1121.699951171875, 1122.719970703125, 1107.0, 1113.199951171875, 1200900], [1109.8599853515623, 1126.5699462890625, 1109.719970703125, 1125.3699951171877, 2538700], [1120.0, 1123.5699462890623, 1113.31005859375, 1116.699951171875, 1211800], [1115.0799560546877, 1115.699951171875, 1084.5999755859377, 1087.5799560546877, 1582200], [1091.0, 1095.1199951171877, 1073.68994140625, 1080.3199462890623, 1734900], [1086.75, 1088.4599609375, 1075.8499755859377, 1076.6300048828123, 1203900]]
43

In [33]:
trend = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trend.append(1)
    elif row[3] - row[0] < 0:
        trend.append(-1)
    elif row[3] - row[0] == 0:
        trend.append(0)
            
print(trend)
print(len(trend))
          
trendString = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trendString.append('Positive')
    elif row[3] - row[0] < 0:
        trendString.append('Negative')
    elif row[3] - row[0] == 0:
        trendString.append('Neutral')
        
print(trendString)

[-1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1]
43
['Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Negative', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative']

In [34]:
data["Trend"] = trend
data["TrendString"] = trendString

In [35]:
data.to_csv(r'C:\Users\Vinod\Desktop\major project\google_stocks.csv')

In [36]:
data = pd.read_csv(r"C:\Users\Vinod\Desktop\major project\microsoft_stocks.csv")


Row_list =[] 
#Row_list1 = []

# Iterate over each row 
for index, rows in data.iterrows(): 
    # Create list for the current row 
    my_list =[rows['Open'], rows['High'], rows['Low'], rows['Close'], rows['Volume']] 
    
    # append the list to the final list 
    Row_list.append(my_list)
    
print(Row_list[:10])
print(len(Row_list))

[[129.39935795453073, 130.89626456223513, 128.79277264203202, 129.58525085449222, 17821700], [129.7613654373012, 130.83756470387266, 129.66352235454087, 129.97660827636722, 14517800], [131.28761219802888, 132.3149047754034, 130.68102693065381, 132.23663330078122, 25934500], [132.08010948453656, 132.98998751740325, 130.91584539010842, 132.75518798828122, 23744400], [134.47706994502303, 134.68253439156118, 132.78449255963054, 133.98788452148438, 33042600], [133.6259127145245, 134.75103339085857, 133.5085129719524, 134.00747680664062, 36727900], [134.03682907786103, 135.40654252759185, 134.03682907786103, 134.79995727539062, 20628800], [134.2814212940113, 134.61406385493447, 129.85918014311102, 130.54403686523438, 33327400], [131.44417794659955, 132.8041133304345, 130.71039953959306, 131.03324890136722, 23657700], [131.2386805270159, 131.79635914235502, 130.62230204243193, 131.24845886230472, 16557500]]
43

In [37]:
trend = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trend.append(1)
    elif row[3] - row[0] < 0:
        trend.append(-1)
    elif row[3] - row[0] == 0:
        trend.append(0)
            
print(trend)
print(len(trend))
          
trendString = []
for row in Row_list:
    if row[3] - row[0] > 0:
        trendString.append('Positive')
    elif row[3] - row[0] < 0:
        trendString.append('Negative')
    elif row[3] - row[0] == 0:
        trendString.append('Neutral')
        
print(trendString)

[1, 1, 1, 1, -1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1]
43
['Positive', 'Positive', 'Positive', 'Positive', 'Negative', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative', 'Negative', 'Positive', 'Positive', 'Positive', 'Negative', 'Negative', 'Positive', 'Negative']